# Generated by Django 5.0.14 on 2026-01-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_name', models.CharField(max_length=255)),
                ('research_name_uz', models.CharField(max_length=255, null=True)),
                ('research_name_en', models.CharField(max_length=255, null=True)),
                ('research_name_tr', models.CharField(max_length=255, null=True)),
                ('research_name_ru', models.CharField(max_length=255, null=True)),
                ('pedagogical_name', models.CharField(max_length=255)),
                ('pedagogical_name_uz', models.CharField(max_length=255, null=True)),
                ('pedagogical_name_en', models.CharField(max_length=255, null=True)),
                ('pedagogical_name_tr', models.CharField(max_length=255, null=True)),
                ('pedagogical_name_ru', models.CharField(max_length=255, null=True)),
                ('model_name', models.CharField(max_length=255)),
                ('model_name_uz', models.CharField(max_length=255, null=True)),
                ('model_name_en', models.CharField(max_length=255, null=True)),
                ('model_name_tr', models.CharField(max_length=255, null=True)),
                ('model_name_ru', models.CharField(max_length=255, null=True)),
                ('student_name', models.CharField(max_length=255)),
                ('student_name_uz', models.CharField(max_length=255, null=True)),
                ('student_name_en', models.CharField(max_length=255, null=True)),
                ('student_name_tr', models.CharField(max_length=255, null=True)),
                ('student_name_ru', models.CharField(max_length=255, null=True)),
                ('monitor_name', models.CharField(max_length=255)),
                ('monitor_name_uz', models.CharField(max_length=255, null=True)),
                ('monitor_name_en', models.CharField(max_length=255, null=True)),
                ('monitor_name_tr', models.CharField(max_length=255, null=True)),
                ('monitor_name_ru', models.CharField(max_length=255, null=True)),
                ('multimedia_name', models.CharField(max_length=255)),
                ('multimedia_name_uz', models.CharField(max_length=255, null=True)),
                ('multimedia_name_en', models.CharField(max_length=255, null=True)),
                ('multimedia_name_tr', models.CharField(max_length=255, null=True)),
                ('multimedia_name_ru', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
